# compose syntax version.
version: "3.3"

# services declaration.
services:
  # iperf3 Server
  server:
    container_name: local_baseline_server
    build: ../images/Baseline
    image: mentz/tcc:baseline
    entrypoint: sh -c "iperf3 -s1 >> /dev/null"
    network_mode: host

  # iperf3 Client
  client:
    container_name: local_baseline_client
    build: ../images/Baseline
    image: mentz/tcc:baseline
    entrypoint: sh -c "iperf3 -c localhost -t 120 -V -J > /root/logs/log.json"
    network_mode: host
    depends_on:
      - server
    volumes:
      - ./log/:/root/logs
# networks:
#   default:
#     driver: bridge
